/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iCoinMingleLpSol from "./ICoinMingleLP.sol";
export type { iCoinMingleLpSol };
export type { IWFTM } from "./IWFTM";
